package pt.quickLabPIV.interpolators;

import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;

import pt.quickLabPIV.Matrix;
import pt.quickLabPIV.PIVContextSingleton;
import pt.quickLabPIV.PIVContextTestsSingleton;
import pt.quickLabPIV.interpolators.Gaussian2DSubTypeFactoryEnum;
import pt.quickLabPIV.interpolators.IBasicCrossCorrelationInterpolator;
import pt.quickLabPIV.interpolators.ICrossCorrelationInterpolator;
import pt.quickLabPIV.maximum.MaxCrossResult;

/**
 * Provides unit tests to validate interpolation with a Assymmetric standard deviation 2D Gaussian function, over a matrix of 7x7 pixels generated by
 * a 2D Symmetric Gaussian function with no noise added.
 * 
 * @author lpnm
 */
public class Gaussian2DAssymmetricInterpolatorAdvanced7PixelsSymmetricTest {
    private static final int DIM_X = 7;
    private static final int DIM_Y = 7;
    private static final Gaussian2DSubTypeFactoryEnum TYPE1 = Gaussian2DSubTypeFactoryEnum.Assymmetric;

    public IBasicCrossCorrelationInterpolator simpleAdapter(ICrossCorrelationInterpolator interp) {
        return new IBasicCrossCorrelationInterpolator() {
            private ICrossCorrelationInterpolator _interp = interp;
            
            @Override
            public MaxCrossResult interpolate(Matrix m, MaxCrossResult result) {
                List<MaxCrossResult> results = new ArrayList<>(1);
                results.add(result);
                results = _interp.interpolate(results);
                return results.get(0);
            }
        };
    }
    
    @Before
    public void setup() {
        PIVContextTestsSingleton.setSingleton();        
    }
    
    @Test
    public void centeredSigma10() {
        float uX = 0.0f;
        float uY = 0.0f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }
    
    //Left Sigma 10
    
    @Test
    public void deviated01LeftSigma10() {
        float uX = -0.1f;
        float uY = -0.1f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02LeftSigma10() {
        float uX = -0.2f;
        float uY = -0.2f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03LeftSigma10() {
        float uX = -0.3f;
        float uY = -0.3f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04LeftSigma10() {
        float uX = -0.4f;
        float uY = -0.4f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05LeftSigma10() {
        float uX = -0.5f;
        float uY = -0.5f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    //Right Sigma 10
    
    @Test
    public void deviated01RightSigma10() {
        float uX = 0.1f;
        float uY = 0.1f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02RightSigma10() {
        float uX = 0.2f;
        float uY = 0.2f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03RightSigma10() {
        float uX = 0.3f;
        float uY = 0.3f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04RightSigma10() {
        float uX = 0.4f;
        float uY = 0.4f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05RightSigma10() {
        float uX = 0.5f;
        float uY = 0.5f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    //Sigma 05
    
    @Test
    public void centeredSigma05() {
        float uX = 0.0f;
        float uY = 0.0f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }
    
    //Left Sigma 05
    
    @Test
    public void deviated01LeftSigma05() {
        float uX = -0.1f;
        float uY = -0.1f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02LeftSigma05() {
        float uX = -0.2f;
        float uY = -0.2f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03LeftSigma05() {
        float uX = -0.3f;
        float uY = -0.3f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04LeftSigma05() {
        float uX = -0.4f;
        float uY = -0.4f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05LeftSigma05() {
        float uX = -0.5f;
        float uY = -0.5f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    //Right Sigma 05
    
    @Test
    public void deviated01RightSigma05() {
        float uX = 0.1f;
        float uY = 0.1f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02RightSigma05() {
        float uX = 0.2f;
        float uY = 0.2f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03RightSigma05() {
        float uX = 0.3f;
        float uY = 0.3f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04RightSigma05() {
        float uX = 0.4f;
        float uY = 0.4f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05RightSigma05() {
        float uX = 0.5f;
        float uY = 0.5f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    
    //Sigma 01
    
    @Test
    public void centeredSigma02() {
        float uX = 0.0f;
        float uY = 0.0f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }
    
    //Left Sigma 01
    
    @Test
    public void deviated01LeftSigma03() {
        float uX = -0.1f;
        float uY = -0.1f;
        float sigmaX = 0.35f;
        float sigmaY = 0.35f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02LeftSigma02() {
        float uX = -0.2f;
        float uY = -0.2f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03LeftSigma02() {
        float uX = -0.3f;
        float uY = -0.3f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04LeftSigma02() {
        float uX = -0.4f;
        float uY = -0.4f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05LeftSigma02() {
        float uX = -0.5f;
        float uY = -0.5f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    //Right Sigma 01
    
    @Test
    public void deviated01RightSigma03() {
        float uX = 0.1f;
        float uY = 0.1f;
        float sigmaX = 0.35f;
        float sigmaY = 0.35f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
       assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02RightSigma02() {
        float uX = 0.2f;
        float uY = 0.2f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03RightSigma02() {
        float uX = 0.3f;
        float uY = 0.3f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04RightSigma02() {
        float uX = 0.4f;
        float uY = 0.4f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05RightSigma02() {
        float uX = 0.5f;
        float uY = 0.5f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    
    /****************************
     * Assymetric deviation
     ****************************/
       
    //Left, Bottom Sigma 10
    
    @Test
    public void deviated01LeftBottomSigma10() {
        float uX = -0.1f;
        float uY = +0.1f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02LeftBottomSigma10() {
        float uX = -0.2f;
        float uY = +0.2f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03LeftBottomSigma10() {
        float uX = -0.3f;
        float uY = +0.3f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04LeftBottomSigma10() {
        float uX = -0.4f;
        float uY = +0.4f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05LeftBottomSigma10() {
        float uX = -0.5f;
        float uY = +0.5f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    //Right Bottom Sigma 10
    
    @Test
    public void deviated01RightBottomSigma10() {
        float uX = 0.1f;
        float uY = -0.1f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02RightBottomSigma10() {
        float uX = 0.2f;
        float uY = -0.2f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03RightBottomSigma10() {
        float uX = 0.3f;
        float uY = -0.3f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04RightBottomSigma10() {
        float uX = 0.4f;
        float uY = -0.4f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05RightBottomSigma10() {
        float uX = 0.5f;
        float uY = -0.5f;
        float sigmaX = 1.0f;
        float sigmaY = 1.0f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    //Sigma 05    
    //Left Bottom Sigma 05
    
    @Test
    public void deviated01LeftBottomSigma05() {
        float uX = -0.1f;
        float uY = 0.1f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
       assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02LeftBottomSigma05() {
        float uX = -0.2f;
        float uY = 0.2f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03LeftBottomSigma05() {
        float uX = -0.3f;
        float uY = 0.3f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04LeftBottomSigma05() {
        float uX = -0.4f;
        float uY = 0.4f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05LeftBottomSigma05() {
        float uX = -0.5f;
        float uY = 0.5f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    //Right Sigma 05
    
    @Test
    public void deviated01RightBottomSigma05() {
        float uX = 0.1f;
        float uY = -0.1f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02RightBottomSigma05() {
        float uX = 0.2f;
        float uY = -0.2f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03RightBottomSigma05() {
        float uX = 0.3f;
        float uY = -0.3f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04RightBottomSigma05() {
        float uX = 0.4f;
        float uY = -0.4f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05RightBottomSigma05() {
        float uX = 0.5f;
        float uY = -0.5f;
        float sigmaX = 0.5f;
        float sigmaY = 0.5f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    
    //Sigma 01
        
    //Left Bottom Sigma 01
    
    @Test
    public void deviated01LeftBottomSigma02() {
        float uX = -0.1f;
        float uY = 0.1f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02LeftBottomSigma02() {
        float uX = -0.2f;
        float uY = 0.2f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03LeftBottomSigma02() {
        float uX = -0.3f;
        float uY = 0.3f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04LeftBottomSigma02() {
        float uX = -0.4f;
        float uY = 0.4f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05LeftBottomSigma02() {
        float uX = -0.5f;
        float uY = 0.5f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    //Right Bottom Sigma 01
    
    @Test
    public void deviated01RightBottomSigma02() {
        float uX = 0.1f;
        float uY = -0.1f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated02RightBottomSigma02() {
        float uX = 0.2f;
        float uY = -0.2f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated03RightBottomSigma02() {
        float uX = 0.3f;
        float uY = -0.3f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated04RightBottomSigma02() {
        float uX = 0.4f;
        float uY = -0.4f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

    @Test
    public void deviated05RightBottomSigma02() {
        float uX = 0.5f;
        float uY = -0.5f;
        float sigmaX = 0.25f;
        float sigmaY = 0.25f;
        PIVContextSingleton context = PIVContextSingleton.getSingleton();
        Matrix matrix = GaussianTestHelper.createMatrixWithGaussian2DAssymmetric(DIM_X, DIM_Y, uX, sigmaX, uY, sigmaY);
        MaxCrossResult result = GaussianTestHelper.setupPIVContext(context, DIM_X, DIM_Y, TYPE1);
         result.setCrossMatrix(matrix);
        
        IBasicCrossCorrelationInterpolator interpolator = simpleAdapter(context.getPIVReusableObjects().getOrCreateInterpolator());
        result = interpolator.interpolate(matrix, result);
        System.out.println(result);      
        
        assertEquals("Interpolation incorrectly deviated in I direction from integer max.", uY + (float)(DIM_Y/2), result.getMainPeakI(), 8e-3f);
        assertEquals("Interpolation incorrectly deviated in J direction from integer max.", uX + (float)(DIM_X/2), result.getMainPeakJ(), 8e-3f);
    }

}
